services:
  - type: web
    name: dicel-erp-backend
    env: node
    nodeVersion: 18.17.0
    buildCommand: npm install --production && npm run build && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: dicel_erp_jwt_secret_key_2024_secure_token_!@#$%^&*()
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: API_PREFIX
        value: /api/v1
      - key: ALLOWED_ORIGINS
        value: https://dicel-erp.netlify.app,http://localhost:3000,http://localhost:5001
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health 